name       : python-stevedore
version    : 3.5.0
release    : 8
source     :
    - https://pypi.io/packages/source/s/stevedore/stevedore-3.5.0.tar.gz : f40253887d8712eaa2bb0ea3830374416736dc8ec0e22f5a65092c1174c44335
license    : Apache-2.0
component  : programming.python
summary    : Manage dynamic plugins for Python applications
description: |
    Manage dynamic plugins for Python applications
builddeps  :
    - pkgconfig(python3)
    - pbr
    - python-docutils # check
    - python-pytest # check
    - python-sphinx # check
rundeps    :
    - pbr
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    #need testtools packaged
    rm $workdir/stevedore/tests/test_callback.py
    %python3_test pytest3
