name       : python-stevedore
version    : 1.30.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/s/stevedore/stevedore-1.30.0.tar.gz : b92bc7add1a53fb76c634a178978d113330aaf2006f9498d9e2414b31fbfc104
license    : Apache-2.0
component  : programming.python
summary    : Manage dynamic plugins for Python applications
description: |
    Manage dynamic plugins for Python applications
builddeps  :
    - pkgconfig(python3)
    - pbr
    - python-setuptools
rundeps    :
    - pbr
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
