name       : python-stevedore
version    : 1.17.1
release    : 2
source     :
    - https://pypi.python.org/packages/98/33/2c8003cb4294d1729bfb6cdf4bbfe74b968403b2df0a80ee876bebf20488/stevedore-1.17.1.tar.gz : 79414e27ece996b2e81161c1ec91536f2b15645d5f6bd28128724486e1c4b8e3
license    : Apache-2.0
component  : programming.python
summary    : Manage dynamic plugins for Python applications
description: |
    Manage dynamic plugins for Python applications
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - pbr
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
