name       : python-stevedore
version    : 1.31.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/05/79/516aa1c427da04f818242ec147a2f417dd0e8f4abbc9302ed07459fb152d/stevedore-1.31.0.tar.gz : e0739f9739a681c7a1fda76a102b65295e96a144ccdb552f2ae03c5f0abe8a14
license    : Apache-2.0
component  : programming.python
summary    : Manage dynamic plugins for Python applications
description: |
    Manage dynamic plugins for Python applications
builddeps  :
    - pkgconfig(python3)
    - pbr
    - python-setuptools
rundeps    :
    - pbr
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
